import { generateImages, saveProject } from '../api.js';
import { createBeforeAfterSlider } from '../components/BeforeAfterSlider.js';

/**
 * Before/After page
 *
 * Shows a drag-to-reveal slider comparing the user's original photo (before)
 * with a DALL-E generated aspirational vision (after).
 *
 * IMPORTANT HONESTY LABEL: The "after" image is clearly labelled as an
 * "AI inspiration — an organized vision" rather than a literal prediction
 * of the user's transformed space. DALL-E generates from text, not from
 * the user's actual photo.
 */
export async function beforeAfterPage() {
  const container = document.createElement('div');
  container.className = 'page before-after-page';

  container.innerHTML = `
    <div class="page-header">
      <h2>Before &amp; After</h2>
      <p>Your space alongside an AI-generated organized vision.</p>
    </div>

    <div id="baContent">
      <div class="loading-state">
        <div class="spinner">
          <svg width="36" height="36" viewBox="0 0 36 36" fill="none">
            <circle cx="18" cy="18" r="14" stroke="rgba(255,255,255,0.1)" stroke-width="3"/>
            <path d="M32 18 A14 14 0 0 0 18 4" stroke="#E91E63" stroke-width="3" stroke-linecap="round"/>
          </svg>
        </div>
        <p>Generating your organized vision…</p>
        <span class="text-muted" style="font-size:0.78rem">DALL-E is crafting an inspiration image</span>
      </div>
    </div>
  `;

  const contentEl = container.querySelector('#baContent');

  // Retrieve data from sessionStorage
  let analysis, photoBase64, photoMime;
  try {
    analysis     = JSON.parse(sessionStorage.getItem('athena_analysis') || 'null');
    photoBase64  = sessionStorage.getItem('athena_photo_base64') || null;
    photoMime    = sessionStorage.getItem('athena_photo_mime') || 'image/jpeg';
  } catch {
    analysis = null;
  }

  if (!analysis) {
    contentEl.innerHTML = `
      <div class="empty-state">
        <div class="empty-state__icon">🖼️</div>
        <p class="empty-state__title">No analysis found</p>
        <p>Scan a space first to generate your before &amp; after vision.</p>
        <button class="btn btn--primary mt-16" id="goScan">Scan a Space</button>
      </div>
    `;
    contentEl.querySelector('#goScan')?.addEventListener('click', () => {
      window.location.hash = '#/camera';
    });
    return container;
  }

  const planSummary = analysis.summary || analysis.issues?.join('. ') || 'A cluttered space needing organization.';

  try {
    const { afterImageUrl } = await generateImages({
      originalImageBase64: photoBase64 || undefined,
      planSummary,
    });

    // Build before image data URL if we have the base64
    const beforeSrc = photoBase64
      ? `data:${photoMime};base64,${photoBase64}`
      : null;

    contentEl.innerHTML = '';

    // ── Disclaimer banner (honest labeling) ───────────────────────
    const disclaimer = document.createElement('div');
    disclaimer.className = 'ba-disclaimer';
    disclaimer.innerHTML = `
      <span class="ba-disclaimer__icon">ℹ️</span>
      <span>
        <strong>AI Inspiration Image</strong> — The "After" view is a photorealistic
        vision generated by DALL-E based on your analysis. It shows what a beautifully
        organised space <em>could</em> look like — it is not a literal transformation
        of your specific room.
      </span>
    `;
    contentEl.appendChild(disclaimer);

    // ── Slider wrapper ────────────────────────────────────────────
    const sliderWrap = document.createElement('div');
    sliderWrap.className = 'ba-slider-wrap';
    sliderWrap.style.position = 'relative';

    if (beforeSrc && afterImageUrl) {
      // Full interactive slider
      const slider = createBeforeAfterSlider(beforeSrc, afterImageUrl);
      sliderWrap.appendChild(slider);

      // Floating labels
      const beforeLabel = document.createElement('div');
      beforeLabel.className = 'ba-label ba-label--before';
      beforeLabel.innerHTML = `<span>Before</span>`;
      sliderWrap.appendChild(beforeLabel);

      const afterLabel = document.createElement('div');
      afterLabel.className = 'ba-label ba-label--after';
      afterLabel.innerHTML = `<span>✨ AI Inspiration</span>`;
      sliderWrap.appendChild(afterLabel);

      // Drag hint
      const dragHint = document.createElement('p');
      dragHint.style.cssText = 'text-align:center;font-size:0.78rem;color:var(--text-muted);margin-top:8px;';
      dragHint.textContent = '← Drag to compare →';
      contentEl.appendChild(sliderWrap);
      contentEl.appendChild(dragHint);
    } else {
      // Fallback: show just the after image if no before photo
      const img = document.createElement('img');
      img.src = afterImageUrl;
      img.alt = 'AI inspiration — an organized vision';
      img.style.cssText = 'width:100%;border-radius:var(--radius-lg);';
      sliderWrap.appendChild(img);

      const afterLabel = document.createElement('div');
      afterLabel.className = 'ba-label ba-label--after';
      afterLabel.innerHTML = `<span>✨ AI Inspiration</span>`;
      sliderWrap.appendChild(afterLabel);
      contentEl.appendChild(sliderWrap);
    }

    // ── Analysis summary card ─────────────────────────────────────
    if (analysis.summary) {
      const summaryCard = document.createElement('div');
      summaryCard.className = 'card';
      summaryCard.innerHTML = `
        <p style="font-size:0.75rem;font-weight:600;text-transform:uppercase;letter-spacing:0.07em;color:var(--text-sec);margin-bottom:8px;">
          Organization Plan
        </p>
        <p style="font-size:0.9rem;color:var(--text-sec);line-height:1.6;">${escHtml(analysis.summary)}</p>
      `;
      contentEl.appendChild(summaryCard);
    }

    // ── Apply / Save CTA ──────────────────────────────────────────
    const ctaWrap = document.createElement('div');
    ctaWrap.innerHTML = `
      <button class="btn btn--primary btn--full" id="applyBtn">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/>
          <polyline points="17 21 17 13 7 13 7 21"/>
          <polyline points="7 3 7 8 15 8"/>
        </svg>
        Save This Project
      </button>
      <div id="saveStatus" style="text-align:center;margin-top:8px;font-size:0.82rem;color:var(--text-sec);"></div>
    `;
    contentEl.appendChild(ctaWrap);

    // Save handler
    ctaWrap.querySelector('#applyBtn').addEventListener('click', async () => {
      const btn = ctaWrap.querySelector('#applyBtn');
      const statusEl = ctaWrap.querySelector('#saveStatus');
      btn.disabled = true;
      btn.textContent = 'Saving…';
      statusEl.textContent = '';

      try {
        let recommendations = null;
        try {
          recommendations = JSON.parse(sessionStorage.getItem('athena_recommendations') || 'null');
        } catch { /* ignore */ }

        await saveProject({
          project: {
            name: `Space ${new Date().toLocaleDateString()}`,
            score: analysis.score,
            status: 'analyzed',
          },
          analysis: {
            issues:            analysis.issues || [],
            recommendations:   recommendations || [],
            before_image_url:  null, // base64 not persisted per non-goal spec
            after_image_url:   afterImageUrl,
          },
        });

        btn.textContent = '✓ Saved';
        statusEl.textContent = 'Project saved to your history.';

        // Navigate to scans after brief delay
        setTimeout(() => { window.location.hash = '#/scans'; }, 1200);
      } catch (err) {
        btn.disabled = false;
        btn.textContent = 'Save This Project';
        statusEl.textContent = `Save failed: ${escHtml(err.message)}`;
      }
    });

  } catch (err) {
    contentEl.innerHTML = `
      <div class="error-state">
        Failed to generate inspiration image: ${escHtml(err.message)}
        <br><br>
        <button class="btn btn--secondary" onclick="history.back()">← Go Back</button>
      </div>
    `;
  }

  return container;
}

function escHtml(str) {
  if (str == null) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
